export const ApplicationWorkflow = {
  DRAFT: ['SUBMITTED'],

  SUBMITTED: ['REGISTRAR_REVIEW'],

  REGISTRAR_REVIEW: ['REVIEWER_REVIEW', 'REJECTED'],

  REVIEWER_REVIEW: ['PAYMENT_PENDING', 'REJECTED'],

  PAYMENT_PENDING: ['PAYMENT_VERIFIED'],

  PAYMENT_VERIFIED: ['FINANCE_APPROVAL'],

  FINANCE_APPROVAL: ['ADMIN_REVIEW'],

  ADMIN_REVIEW: ['APPROVED', 'REJECTED'],
};
